# Generated by Django 3.2.3 on 2021-06-03 09:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0002_auto_20210603_1403'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Incomes',
            new_name='Income',
        ),
    ]
